<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kdssass"
 *
 * Auto generated by Extension Builder 2018-03-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'kdssass',
    'description' => 'Sass Compiler Service',
    'category' => 'services',
    'author' => 'Oliver Kurth',
    'author_email' => 'info@kds-kassel.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.0.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
